CREATE OR REPLACE PROCEDURE PROC_RETORNANOMEFUNC(
	P_ID IN NUMBER, 
	P_NOME OUT HR.EMPLOYEES.FIRST_NAME%TYPE) 
-- CRIAR OU ATUALIZAR A PROCEDURE

AS -- OU  IS = DECLARE

	V_FIRST_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
  	V_EMAIL HR.EMPLOYEES.EMAIL%TYPE;

BEGIN

	SELECT FIRST_NAME, EMAIL INTO V_FIRST_NAME, V_EMAIL
	   FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = P_ID;

	P_NOME := V_FIRST_NAME;

END;


-- PARA EXECUTAR


DECLARE 
  V_RET HR.EMPLOYEES.FIRST_NAME%TYPE; -- VARIAVEL DE RETORNO
  
BEGIN 

	HR.PROC_RETORNANOMEFUNC(101, V_RET);
  	
  	DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONÁRIO É: '|| V_RET);

END;